USE [master]
GO

/****** Object:  Database [dbBoleto]    Script Date: 08/02/2019 22:51:58 ******/
CREATE DATABASE [dbBoleto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbBoleto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\dbBoleto.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbBoleto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\dbBoleto_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbBoleto] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbBoleto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbBoleto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbBoleto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbBoleto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbBoleto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbBoleto] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbBoleto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbBoleto] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dbBoleto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbBoleto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbBoleto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbBoleto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbBoleto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbBoleto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbBoleto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbBoleto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbBoleto] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbBoleto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbBoleto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbBoleto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbBoleto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbBoleto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbBoleto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbBoleto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbBoleto] SET RECOVERY FULL 
GO

ALTER DATABASE [dbBoleto] SET  MULTI_USER 
GO

ALTER DATABASE [dbBoleto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbBoleto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbBoleto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbBoleto] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbBoleto] SET  READ_WRITE 
GO


USE [dbBoleto]
GO

/****** Object:  Table [dbo].[BradescoIntegration]    Script Date: 08/02/2019 22:54:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BradescoIntegrations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [nvarchar](50) NOT NULL,
	[Token] [nvarchar](max) NOT NULL,
	[IsRequest] [bit] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[JsonContent] [nvarchar](max) NOT NULL,
	[UrlBoleto] [nvarchar](max) NULL,
 CONSTRAINT [PK_BradescoIntegrations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
